config/routes.rb
Rails.application.routes.draw do
  
  resources :books do
    member do
      get :delete
    end
  end


  resources :authors do
    member do
      get :delete
    end
  end


 # get 'authors/index'
 # get 'authors/show'
 # get 'authors/new'  #create
 # get 'authors/edit'  #update
 # get 'authors/delete' #destroy

  root 'authors#index' #carga por defecto   
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord

	has_many :books  #Un autor tiene varios libros

	mount_uploader :avatar, AvatarUploader

	EMAIL_REGEX = /\A[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,4}\Z/i

	validates :correo, 		:presence => true,
							:format => EMAIL_REGEX

end

app/models/book.rb
class Book < ApplicationRecord

	belongs_to :author

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  def index
    @authors = Author.all

    if params[:nombre] || params[:apellido]
      nombre = params[:nombre]
      apellido = params[:apellido]
      @authors = Author.where(["nombre LIKE ? AND apellido LIKE?", "%#{nombre}%","%#{apellido}%"])
    else
      @authors = Author.all
    end
    
  end

  def show
    @author = Author.find(params[:id])
  end

  def new
    @author = Author.new
  end

  
  def update
    @author = Author.find(params[:id])
    if @author.update_attributes(author_params)
      redirect_to(author_path(@author))
    else
       render('edit')
    end
  end

  
  def create
    @author = Author.create(author_params)
    if @author.save 
      redirect_to(authors_path)
    else
      render 'new'
    end
  end


  def edit
    @author = Author.find(params[:id])
    
  end

  def delete
  end


  private 

  def author_params
    params.require(:author).permit(:nombre, :apellido, :correo, :avatar)
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController


  before_action :find_author
  #, :only => [:index, :show]
  #, :except => [:new]

  def index

    #@author = Author.find(params[:author_id])
    @books = @author.books  #esto lo lee ya que en el modelo existe la relación
    #Obtener el id del author en los parametros
    #obtener el author con el id recibido
    #buscar los libros del autor
  end

  def show
    #@author = Author.find(params[:author_id])
    @book = Book.find(params[:id])  #Find busca por un id
    #if @book == nil
    #  redirect_to books_path   #Lo que hace es redirige en caso no haya valor de book
  end

  def new
    #@author = Author.find(params[:author_id])
    @book = Book.new(:author_id => @author.id)
    #@authors = []
    #Author.all.map { |author| @authors.append([author.nombre, author.id]) }
  end

  def create
    #@author = Author.find(params[:author_id])
    @book = Book.create(book_params)
    @book.author = @author
    if @book.save 
      redirect_to(books_path(:author_id => @author.id))
    else
      render 'new'
    end
  end

  def edit
    #@author = Author.find(params[:author_id])
    @book = Book.find(params[:id])
    #@authors = []  
    #Author.all.map { |author| @authors.append([author.nombre, author.id]) } 
    #Internamente se recorre todos los autores y crea un array que contenga el nombre y id de cada autor
  
  end

  def update
    #@author = Author.find(params[:author_id])
    @book = Book.find(params[:id])
    if @book.update_attributes(book_params)
      redirect_to(book_path(@book, :author_id => @author.id))
    else
      @authors = []  #se vuelve a generar el array de author, si no se hace lo va a buscar 
      # y se mostrará un error
      Author.all.map { |author| @authors.append([author.nombre, author.id]) } 
      #map recorre todos los autores y crea el arreglo
      render('edit')
    end
  end

  def delete
  end

  private 

  def book_params
    params.require(:book).permit(:titulo, :author_id, :visible, :descripcion, :estado)
  end

  def find_author
    @author = Author.find(params[:author_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/authors/_form.html.erb
<table class="table">
		<tr>
			<th>Nombre</th>
			<td><%= f.text_field(:nombre) %></td>
		</tr>
	    <tr>
			<th>Apellido</th>
			<td><%= f.text_field(:apellido) %></td>
		</tr>
		 <tr>
			<th>Correo</th>
			<td><%= f.email_field(:correo) %></td>
		</tr>
         <tr>
			<th>Avatar</th>
			<%= image_tag(@author.avatar.url, 
						style: 'height:auto;width:300px', 
						alt: 'Avatar') if @author.avatar? 
			%><br>
			<td>
				<%= f.file_field :avatar, accept:'image/*' %><br><br>
			</td>
		</tr>


</table>

app/views/authors/delete.html.erb
<h1>Authors#delete</h1>
<p>Find me in app/views/authors/delete.html.erb</p>

app/views/authors/edit.html.erb
<h2> Actualizar Autor</h2>

<%= form_for(@author) do |f| %>

	<%= render( :partial => "form", :locals => { :f => f }) %>

	<div>
		<%= f.submit("Actualizar Autor") %>
	</div>

<% end %>

app/views/authors/index.html.erb
<h2>Autores</h2>

<div>
	<%= link_to("Crear Autor", new_author_path()) %>
</div>
<br>

<table class="table">
		<tr>
			<td>
				<%= form_tag authors_path, :method => "get" do %>
				Nombre <%= text_field_tag :nombre %>
				Nombre <%= text_field_tag :apellido %>
				<%= submit_tag 'Buscar', name: nil %>
				<% end %>
			</td>
		</tr>
</table>


<div>	
	<table>
		<tr>
			<th>Nombre</th>
			<th>Apellido</th>
			<th>Correo</th>
			<th>Acciones</th>
		</tr>
		<% @authors.each do |author| %>
			<tr>
				<td><%= author.nombre %></td>
				<td><%= author.apellido %></td>
				<td><%= author.correo %></td>
				<td>
					<%= link_to("Mostrar", author_path(author)) %>
					<%= link_to("Editar", edit_author_path(author)) %>
					<%= "Eliminar" %>
					<%= link_to("Ver Libros", books_path(:author_id => author.id)) %>
				</td>
			</tr>
		<% end %>
	</table>
</div>

app/views/authors/new.html.erb
<%= link_to("<<Volver a libros", books_path(:author_id => @author.id)) %>


<h2> Nuevo Autor</h2>

<%= form_for(@author) do |f| %>
	
	<%= render( :partial => "form", :locals => { :f => f }) %>

	<div>
		<%= f.submit("Crear Autor") %>
	</div>

<% end %>

app/views/authors/show.html.erb
<table summary="Section form fields">
  <tr>
    <th>Nombre</th>
    <td><%= @author.nombre %></td>
  </tr>
  <tr>
    <th>Apellido</th>
    <td><%= @author.apellido %></td>
  </tr>
   <tr>
    <th>Correo</th>
    <td><%= @author.correo %></td>
  </tr>
    <tr>
    <th>Avatar</th>
    <td><%= image_tag(@author.avatar.url, 
						style: 'height:auto;width:300px', 
						alt: 'Avatar') if @author.avatar? 
			%><br></td>
  </tr>
 
</table>

app/views/books/_form.html.erb
<table class="table">
		<tr>
			<th>Titulo</th>
			<td><%= f.text_field(:titulo) %></td>
		</tr>
		<tr>
			<th>Autor</th>
			
			<td><%= f.object.author.nombre %></td>
		</tr>
		<tr>
			<th>Visible</th>
			<td><%= f.check_box(:visible) %></td>
		</tr>
		<tr>
			<th>Estado</th>
			<td>
				<%= f.radio_button(:estado, 'Publicado') %> Publicado
				<%= f.radio_button(:estado, 'No Publicado') %> No Publicado
			</td>
		</tr>
		<tr>
			<th>Descripcion</th>
			<td><%= f.text_area(:descripcion, :size => '40x10') %> </td>
		</tr>

</table>

app/views/books/delete.html.erb
<h1>Books#delete</h1>
<p>Find me in app/views/books/delete.html.erb</p>

app/views/books/edit.html.erb
<h2> Actualizar libro</h2>

<%= form_for(@book, :url => book_path(:author_id => @author.id)) do |f| %>

	<%= render( :partial => "form", :locals => { :f => f }) %>

	<div>
		<%= f.submit("Actualizar libro") %>
	</div>

<% end %>

app/views/books/index.html.erb
<h2>Libros</h2>

<div>
	<%= link_to("Crear Libro", new_book_path(:author_id => @author.id)) %>
</div>
<br>

<div>	

	<table>
		<tr>
			<th>Título</th>
			<th>Autor</th>
			<th>Estado</th>
			<th>Acciones</th>
		</tr>
		<% @books.each do |book| %>
			<tr>
				<td><%= book.titulo %></td>
				<td><%= book.author.nombre %></td>
				<td><%= book.estado %></td>
				<td>
					<%= link_to("Mostrar", book_path(book, :author_id => @author.id)) %>
					<%= link_to("Editar", edit_book_path(book, :author_id => @author.id)) %>
					<%= "Eliminar" %>
				</td>
			</tr>
		<% end %>
	</table>
</div>

app/views/books/new.html.erb
<%= link_to("<< Volver a libros", books_path(:author_id => @author.id)) %>

<h2> Nuevo libro</h2>

<%= form_for(@book, :url => books_path(:author_id => @author.id)) do |f| %>
	
	<%= render( :partial => "form", :locals => { :f => f }) %>

	<div>
		<%= f.submit("Crear libro") %>
	</div>

<% end %>

app/views/books/show.html.erb
<%= link_to("<< Volver a libros", books_path(:author_id => @author.id)) %>

<table summary="Section form fields">
  <tr>
    <th>Titulo</th>
    <td><%= @book.titulo %></td>
  </tr>
  <tr>
    <th>Autor</th>
    <td><%= @book.author.nombre %></td>
  </tr>
  <tr>
    <th>Visible</th>
    <td><%= @book.visible ? 'si' : 'no' %></td>
  </tr>
  <tr>
    <th>Estado</th>
    <td>
      <%= @book.estado %>
    </td>
  </tr>
  <tr>
    <th>Descripcion</th>
    <td><%= @book.descripcion %></td>
  </tr>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Libreria</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>